### ISSUE TITLE
CloudMl 

### ISSUE THREAD

**Issue by BabaYara** [automl/HpBandSter#17]
Hello,

So I have been trying to run a google couldml training job using hpbandster over the last couple of days with no success. 

The main problem is that whenever the instance offloads work onto the GPU, hpbandster just hangs. 
If I comment out the "session" part of my neural network implementation (tensorflow) and just return zeros, everything works fine. 
Do you have any idea how I can work around this issue?

**Comment by sfalkner** [comment]
Hello,
what version of tensorflow is running on the cloud? For older version, I remember that Tensorflow needed some extra code to deal with the fact that it is executed in different threads many times (internally each evaluation creates a new thread). If you could provide me the tensorflow version, I could try to check if that is indeed the problem.
Could you also share the worker code with some minimal working example?

BTW, what happens if you run your code locally? Does it also hang?

Best,
Stefan

**Comment by sfalkner** [comment]
closed due to inactivity from the OP.
