### ISSUE TITLE
random search docstring

### ISSUE THREAD

**Issue by aaronkl** [automl/HpBandSter#23]
Why does hpbandster.optimizer.RandomSearch need a min_budget and max_budget? Also, the docstring doesn't match the actual parameters of the constructor

**Comment by sfalkner** [comment]
Good question. So there are two reasons for that:
1. so that you can simply replace HyperBand or BOHB by RandomSearch without changing anything
2. the number of configs per iteration is adjusted such that an iteration of RandomSearch takes (roughly) the same budget as an iteration of BOHB.

Does that make sense?

I have no good excuse for the docstring though :)
But I shall change that and also add an explanation for the budgets.

**Comment by aaronkl** [comment]
hmm so what happens if let's say min_budget = 1 , max_budget = 27 and number of iterations =1 ? Does random search then performs 3 function evaluations on the full budget (which is if I am not mistaken the same budget as BO-HB uses) or just 1 function evaluation?

**Comment by sfalkner** [comment]
You are right, it would do 4 full function evaluations.
How would you feel about the following behavior:
- if min and max budget are specified, it uses the same resources as a BOHB/Hyperband iteration
- if only the max budget is specified, it will do one function evaluation per iteration
That way, one can still substitute the optimizers for one another, but can also get the number of evaluations match the number of iterations.

**Comment by aaronkl** [comment]
ok sounds good to me
