### ISSUE TITLE
Workers die randomly

### ISSUE THREAD

**Issue by ifed-ucsd** [automl/HpBandSter#26]
I'm experiencing some strange behavior with workers dying randomly during optimization. Is there some timeout parameter that needs to be modified somewhere?

**Comment by sfalkner** [comment]
Without any further details, it's hard to be helpful. If you did not specify the timeout argument for the worker, they should not shut themselves down. Could it be that the workers crash because your compute method somehow kills the python process. HpBandSter tries to catch any exception thrown in your code, but could there be a core dump or something similar? Could you maybe check the return status of the worker process. If your run is fairly long and computations are expensive, consider running it with debug output. That will generate more information that could help me figure out what the problem might be.
