### ISSUE TITLE
Possible indentation mistake

### ISSUE THREAD

**Issue by PatrykChrabaszcz** [automl/HpBandSter#7]
Can you look at the line:
https://github.com/automl/HpBandSter/blob/master/hpbandster/config_generators/bohb.py#L229
I think there should be one indentation less
Right now it returns a random array if everything is fine

**Comment by sfalkner** [comment]
Hey Patryk,
what do you mean by 'random array if everything is fine'?
So the function tries to impute NaNs in the configurations that are due to conditionalities.
It's a temporary hack to fit our ConfigSpace data into the statsmodels KDE. So it should fill up your array and replace any NaN with a random value for each colum.
Is that not the behavior you see? Can you send me a MWE to check?

**Comment by PatrykChrabaszcz** [comment]
Try to see what happens when your array has no NaNs, you create an empty array which has random values, then row by row you take the datum from the original array but actually never assign it to the output array. Simply remove 1 tab from the line 229 (I think that was intended at the beginning)

**Comment by sfalkner** [comment]
you are right, fixed via 781b6c3baecfe3f82f8baf27719892edad189c4d
